name: "Hello World"

on:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

env:
  OPS: devops

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: List Files
        run: |
          pwd
          ls -lha
      - name: input variables
        env:
          ENV: Produção
        run: |
          echo ${ENV}
          echo ${OPS}



