
name: "Hello World"

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before
        run: |
          ls -lha
      - name: checkout
        uses: actions/checkout@v2
      - name: List Files after
        run: |
          ls -lha


