
name: "Hello World"

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Files
    steps:
      - uses: actions/checkout@v2
      - run: ls -lha

